// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/oleksiyp/prefixrouter/pkg/client/clientset/versioned/typed/prefixrouter/v1beta1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakePrefixrouterV1beta1 struct {
	*testing.Fake
}

func (c *FakePrefixrouterV1beta1) Routes(namespace string) v1beta1.RouteInterface {
	return &FakeRoutes{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakePrefixrouterV1beta1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
