apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: routes.prefixrouter.app
  annotations:
    helm.sh/resource-policy: keep
spec:
  group: prefixrouter.app
  version: v1beta1
  versions:
    - name: v1beta1
      served: true
      storage: true
  names:
    plural: routes
    singular: route
    kind: Route
    categories:
      - all
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
            - prefix
            - service
          properties:
            prefix:
              description: HTTP prefix
              type: string
            service:
              description: Service to forward traffic
              type: string
